# Generated by Django 2.2.7 on 2019-11-25 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('DoB', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, default='../media/', upload_to='profile_images')),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('hobbies', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bike_hire_docking_station_id', models.CharField(default='0', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiceaterAPI.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', max_length=140)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bike_hire_docking_station_id', models.CharField(default='0', max_length=100)),
                ('answers_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiceaterAPI.Comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiceaterAPI.AppUser')),
            ],
        ),
    ]
