# Generated by Django 2.2.7 on 2019-12-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiceaterAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bike_hire_docking_station_id',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
