# Generated by Django 2.2.7 on 2019-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiceaterAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='stop_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='bike_hire_docking_station_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
