# Generated by Django 2.2.7 on 2019-11-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiceaterAPI', '0002_sum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sum',
        ),
        migrations.AddField(
            model_name='rest',
            name='first_name',
            field=models.CharField(default='Jose', max_length=30),
        ),
        migrations.AddField(
            model_name='rest',
            name='last_name',
            field=models.CharField(default='Martin', max_length=30),
        ),
    ]
