# Generated by Django 2.2.7 on 2019-12-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiceaterAPI', '0002_auto_20191212_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
