# Generated by Django 2.2.7 on 2019-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiceaterAPI', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/media/', upload_to='profile_images'),
        ),
    ]
