# Generated by Django 2.2.7 on 2019-11-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiceaterAPI', '0004_auto_20191113_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answers_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiceaterAPI.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='../media/', upload_to='profile_images'),
        ),
    ]
