# Generated by Django 2.2.7 on 2020-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiceaterAPI', '0004_auto_20191212_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
