# Generated by Django 2.2.7 on 2019-11-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('social_django', '0009_appuser'),
        ('BiceaterAPI', '0006_auto_20191122_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.AppUser'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.AppUser'),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
